### ISSUE TITLE
Entitlement II

### ISSUE THREAD

**Issue by Edugate** [grnet/flowspy#6]
Hi,
I configured flowspy with the the entitlement value 'urn:mace:rediris.es:entitlement:wiki:tfemc2' (for now) and still cannot login, I've added our instance to eduGAIN if somebody wants to try logging in at fod.heanet.ie
Regards
Glenn

**Comment by jkakavas** [comment]
Hi Glenn, 
- fod.heanet.ie is not up ( at least now that I tried to access it)
- Are you releasing urn:mace:rediris.es:entitlement:wiki:tfemc2 as one of the values of the eduPersonEntitlement in your IdP for the user you attempting to log on as ? 
- What is the error you get ? What do the logs say ?

**Comment by Edugate** [comment]
Sorry, fod.heanet.ie is behind our firewall for now. These videos should show what's going on...

https://media.heanet.ie/secure/file/124a783656e3cb6b7259dd9125b5839a
https://media.heanet.ie/secure/file/2c445c2da8609c19297ac5b6745c9a7c

**Comment by jkakavas** [comment]
Hi,

I repeat my previous question: 

Are you releasing urn:mace:rediris.es:entitlement:wiki:tfemc2 as one of the values of the eduPersonEntitlement in your IdP for the user you attempting to log on as ? 

Additionally, media.heanet.ie has federated SSO but it is not published in eduGAIN as an SP so there is no way for us to access it. Please share your videos in another way or (preferably) just describe what the problem is.

**Comment by Edugate** [comment]
You'll see in the videos (with the correct URL now, sorry!) that  urn:mace:rediris.es:entitlement:wiki:tfemc2 is released...
https://media.heanet.ie/page/124a783656e3cb6b7259dd9125b5839a
https://media.heanet.ie/page/2c445c2da8609c19297ac5b6745c9a7c

**Comment by jkakavas** [comment]
Hi again Glenn, 

I can see that the attribute is released but I can't see if it is mapped correctly in your SP. 

A)  What is the value of SHIB_ENTITLEMENT in your settings.py in the #shibboleth attribute map section ?

B)  What is the relevant section in the attribute-map.xml of your Shibboleth Service Provider ? You should have something like 

```
    <Attribute name="urn:mace:dir:attribute-def:eduPersonEntitlement" id="XXXX"/>
    <Attribute name="urn:oid:1.3.6.1.4.1.5923.1.1.1.7" id="XXXX"/>
```

Can you verify that the values for a) and b) above are the same ? That would ensure that FoD knows in which attribute ( available as which header ) to look for the edupersonentitlement

**Comment by Edugate** [comment]
These are the settings...

settings.py:

`SHIB_ENTITLEMENT = ['HTTP_ENTITLEMENT']`

attribute-map.xml

```
    <Attribute name="urn:mace:dir:attribute-def:eduPersonEntitlement" id="entitlement"/>
    <Attribute name="urn:oid:1.3.6.1.4.1.5923.1.1.1.7" id="entitlement"/>
```

**Comment by jkakavas** [comment]
If everything is as you say then it should be able to authenticate you... The relevant part is in https://github.com/grnet/flowspy/blob/085dec60937c022786081f2c059f4cb281a57dc7/flowspec/views.py#L523

Where it gets

``` python
entitlement = lookupShibAttr(settings.SHIB_ENTITLEMENT, request.META)
```

the entitlement value from the request headers. Since settings.SHIB_ENTITLEMENT is ['HTTP_ENTITLEMENT'] as you write and request.META contains HTTP_ENTITLEMENT as seen in your video, the entitlement variable here should get a value. 

However, 

``` python
if settings.SHIB_AUTH_ENTITLEMENT in entitlement.split(";"):
            has_entitlement = True
if not has_entitlement:
            error_entitlement = True
```

the fact that you get the error means that error_entitlement is True which means that either the entitlement didn't get any value above or that 
settings.SHIB_AUTH_ENTITLEMENT value is not the same as HTTP_ENTITLEMENT value.

Can you just verify the values once more just for the sake of it?

**Comment by Edugate** [comment]
triple-checked the values, they are set to match but don't. Is there any way to log output that might show the value of settings.SHIB_AUTH_ENTITLEMENT and entitlement.split(";") ?

**Comment by safts** [comment]
Sure. 
You can use `logger.debug(<variable_name>)`. 

Please note that to do so you need to alter `logging.formatter()` (https://github.com/grnet/flowspy/blob/master/flowspec/views.py#L58) because `clientip`, `user` will not be available and logging will fail. You can set it as
`formatter = logging.Formatter('%(asctime)s %(levelname)s %(message)s')`.

This will output the given variable at `settings.LOG_FILE_LOCATION`/`celery_jobs.log`.

**Comment by Edugate** [comment]
We've got past this issue, which was caused by use introducing a syntax error in the config (and we had not noticed that the pyc file was not being updated). We now have logging and are working on another issue (Something went wrong during user authentication...) and will report back if we are stuck. Thanks!
